name: remindme
description: "Una aplicación de recordatorios elegante y minimalista"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Arquitectura Clean
  get_it: ^8.2.0
  injectable: ^2.3.2

  # Base de datos y persistencia
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2

  # Estado y navegación
  flutter_bloc: ^9.1.1
  go_router: ^16.2.1

  # UI y animaciones
  flutter_animate: ^4.2.0
  lottie: ^3.3.2
  flutter_staggered_animations: ^1.1.1

  # Notificaciones
  flutter_local_notifications: ^19.4.2
  workmanager: ^0.9.0+3
  timezone: ^0.10.1

  # Utilidades
  equatable: ^2.0.5
  intl: ^0.20.2

  # Iconos
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_native_splash: ^2.3.7
  uuid: ^4.5.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1

  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_icon.png
  android: true
  ios: true
  web: false
  android_12:
    color: "#FFFFFF"
    image: assets/images/splash_icon.png
    icon_background_color: "#FFFFFF"

flutter_icons:
  android:
    - "launcher_icon"
    - "adaptive_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/adaptative_foreground.png"
  adaptive_icon_background: "#FFFFFF"
  android_task_switcher_icon: "assets/images/task_switcher.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true

  # Assets que agregaremos más adelante
  assets:
    - assets/images/
  #   - assets/animations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz-wght.ttf
